CREATE TABLE companies
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description TEXT,
    location    VARCHAR(255)                            NOT NULL,
    website     VARCHAR(255),
    logo_url    VARCHAR(255),
    CONSTRAINT pk_companies PRIMARY KEY (id)
);

ALTER TABLE companies
    ADD CONSTRAINT uc_companies_name UNIQUE (name);