CREATE TABLE resumes
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    title      VARCHAR(255),
    file_url   VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_resumes PRIMARY KEY (id)
);

ALTER TABLE job_applications
    ADD resume_id BIGINT;

ALTER TABLE job_applications
    ALTER COLUMN resume_id SET NOT NULL;

ALTER TABLE job_applications
    ADD CONSTRAINT FK_JOB_APPLICATIONS_ON_RESUME FOREIGN KEY (resume_id) REFERENCES resumes (id);