CREATE TABLE user_profiles
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    profile_type    VARCHAR(20)                             NOT NULL,
    full_name       VARCHAR(255)                            NOT NULL,
    phone_number    VARCHAR(255),
    photo_url       VARCHAR(255),
    about           VARCHAR(255),
    country         VARCHAR(50)                             NOT NULL,
    city            VARCHAR(255),
    position        VARCHAR(255)                            NOT NULL,
    experience      VARCHAR(30)                             NOT NULL,
    work_mode       VARCHAR(20)                             NOT NULL,
    format          VARCHAR(20)                             NOT NULL,
    activity_status VARCHAR(20) DEFAULT 'ACTIVE'            NOT NULL,
    portfolio_url   VARCHAR(255),
    user_id         BIGINT                                  NOT NULL,
    CONSTRAINT pk_user_profiles PRIMARY KEY (id)
);

ALTER TABLE resumes
    ADD COLUMN user_profile_id BIGINT;

ALTER TABLE resumes
    ALTER COLUMN user_profile_id SET NOT NULL;

ALTER TABLE resumes
    ADD CONSTRAINT FK_RESUMES_ON_USER_PROFILE FOREIGN KEY (user_profile_id) REFERENCES user_profiles (id);

ALTER TABLE user_profiles
    ADD CONSTRAINT uc_user_profiles_user UNIQUE (user_id);

ALTER TABLE user_profiles
    ADD CONSTRAINT FK_USER_PROFILES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);