CREATE TABLE language_skills
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    language        VARCHAR(30)                             NOT NULL,
    level           VARCHAR(20)                             NOT NULL,
    user_profile_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_language_skills PRIMARY KEY (id)
);

ALTER TABLE user_profiles
    ADD COLUMN language_id BIGINT;

ALTER TABLE user_profiles
    ALTER COLUMN language_id SET NOT NULL;

ALTER TABLE language_skills
    ADD CONSTRAINT FK_LANGUAGE_SKILLS_ON_USER_PROFILE FOREIGN KEY (user_profile_id) REFERENCES user_profiles (id);